services:
  app:
    build: .
    container_name: app
    networks:
      - backend
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - DB_HOST=bolt://db # хост БД из внутренней сети Docker
      - DB_USER=neo4j
      - DB_PASSWORD=password
      - ADMIN_PASSWORD=password
    healthcheck:
      test: curl --fail http://localhost:5000 || exit 1
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 3s
    depends_on:
      db:
        condition: service_healthy

  db:
    image: neo4j:ubi9
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4JLABS_PLUGINS=["apoc"]
    ports:
      - "127.0.0.1:7474:7474" # веб-интерфейс
      - "127.0.0.1:7687:7687" # используется для локальной отладки
    volumes:
      - db-data:/data
      - db-plugins:/plugins
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 10
      start_period: 5s

volumes:
  db-data: { }
  db-plugins: { }

networks:
  backend: { }
