services:
  app:
    build: .
    container_name: app
    networks:
      - backend
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - DB_HOST=bolt://db
    healthcheck:
      test: wget http://localhost:5000 || exit 1
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 5s
    depends_on:
      db:
        condition: service_healthy

  db:
    image: neo4j:ubi9
    environment:
      - NEO4J_AUTH=neo4j/password
    # TODO: закрыть порты после докеризации приложения
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - db-logs:/logs
      - db-config:/config
      - db-data:/data
      - db-plugins:/plugins
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 10
      start_period: 5s

volumes:
  db-logs: { }
  db-config: { }
  db-data: { }
  db-plugins: { }

networks:
  backend: { }